// ════════════════════════════════════════════════════════
// FLUX · config.js — 分类与站点归类配置
// ════════════════════════════════════════════════════════
//
// 使用方法:
//   1) 一级分类: 编辑 CATS 对象（label/icon/order）
//   2) 域名规则: 编辑 RULES 数组（按顺序匹配，第一个命中生效）
//   3) 单站点覆盖: 编辑 SITES 对象（按 URL 精确匹配，优先级最高）
//
// 修改后刷新页面即生效（无需改 data.js）
// ════════════════════════════════════════════════════════

const CONFIG = {
  // ── 1. 一级分类定义（侧边栏显示顺序即此顺序） ──
  cats: {
    ai      : {label:'AI 工具', icon:'🤖'},
    dev     : {label:'开发工具', icon:'💻'},
    edu     : {label:'教育学习', icon:'📚'},
    tools   : {label:'实用工具', icon:'🛠'},
    read    : {label:'阅读书籍', icon:'📖'},
    media   : {label:'影音娱乐', icon:'🎬'},
    audio   : {label:'音乐播客', icon:'🎵'},
    game    : {label:'游戏平台', icon:'🎮'},
    dl      : {label:'软件下载', icon:'⬇️'},
    bt      : {label:'BT 资源', icon:'🌊'},
    mob     : {label:'移动应用', icon:'📱'},
    linux   : {label:'Linux/macOS', icon:'🐧'},
    intl    : {label:'国际社区', icon:'🌍'},
  },

  // ── 2. 域名规则（按顺序匹配，第一个命中即生效） ──
  //   适合批量归类同域名下的所有站点
  //   格式: { domain: "example.com", cat: "dev", tag: "代码托管" }
  rules: [
    {domain:'apple.com', cat:'audio', tag:'音乐平台'},
    {domain:'brew.sh', cat:'dl', tag:'Mac/Linux'},
    {domain:'com.cn', cat:'tools', tag:'壁纸'},
    {domain:'github.com', cat:'dev', tag:'代码托管'},
    {domain:'github.io', cat:'bt', tag:'BT客户端'},
    {domain:'google.com', cat:'ai', tag:'对话AI'},
    {domain:'openai.com', cat:'ai', tag:'对话AI'},
    {domain:'spotify.com', cat:'audio', tag:'音乐平台'},
    {domain:'wikipedia.org', cat:'edu', tag:'知识问答'},
  ],

  // ── 3. 单站点精确覆盖（URL 完整匹配，优先级最高） ──
  //   用于域名规则无法处理的特殊情况
  //   格式: "https://example.com": { cat: "dev", tags: ["代码托管", "免费"] }
  sites: {
    'http://j-so.com': {cat:'media', tags:['网盘搜索']},
    'http://www.laohuabao.com/': {cat:'tools', tags:['tools']},
    'http://www.netbian.com': {cat:'tools', tags:['壁纸']},
    'http://xn--kbtq9uklxgkj.top/': {cat:'bt', tags:['bt']},
    'https://1337x.to': {cat:'bt', tags:['种子搜索']},
    'https://1music.cc/zh-CN': {cat:'audio', tags:['无损下载']},
    'https://33.agilestudio.cn': {cat:'media', tags:['字幕工具']},
    'https://4kdownload.com': {cat:'dl', tags:['视频下载']},
    'https://502book.com': {cat:'read', tags:['电子书']},
    'https://5kep.top': {cat:'media', tags:['网盘搜索']},
    'https://789bh.com/': {cat:'tools', tags:['tools']},
    'https://aistudio.google.com': {cat:'ai', tags:['开发平台']},
    'https://akongwu.com': {cat:'media', tags:['网盘搜索']},
    'https://altstore.io': {cat:'mob', tags:['iOS工具']},
    'https://anchor.fm': {cat:'audio', tags:['播客']},
    'https://ani.pekolove.net': {cat:'media', tags:['动漫']},
    'https://anime1.me': {cat:'media', tags:['动漫']},
    'https://appgallery.huawei.com': {cat:'mob', tags:['应用商店']},
    'https://apps.apple.com': {cat:'mob', tags:['应用商店']},
    'https://archiveofourown.org': {cat:'read', tags:['小说']},
    'https://archlinux.org': {cat:'linux', tags:['发行版']},
    'https://aria2.github.io': {cat:'bt', tags:['BT客户端']},
    'https://assrt.net': {cat:'media', tags:['字幕工具']},
    'https://audiobookbay.lu': {cat:'read', tags:['有声书']},
    'https://bandcamp.com': {cat:'audio', tags:['音乐平台']},
    'https://bangumi.tv': {cat:'read', tags:['动漫']},
    'https://bbc.com': {cat:'intl', tags:['英文媒体']},
    'https://bgmlist.com': {cat:'read', tags:['动漫']},
    'https://bigjpg.com': {cat:'tools', tags:['图片处理']},
    'https://bitwarden.com': {cat:'tools', tags:['隐私安全']},
    'https://books.google.com': {cat:'read', tags:['电子书']},
    'https://brew.sh': {cat:'linux', tags:['macOS']},
    'https://bt.mojiez.net': {cat:'bt', tags:['种子搜索']},
    'https://btdb.to': {cat:'bt', tags:['种子搜索']},
    'https://byrutgame.org': {cat:'game', tags:['单机资源']},
    'https://chat.openai.com': {cat:'ai', tags:['对话AI']},
    'https://chiebukuro.yahoo.co.jp': {cat:'intl', tags:['日语社区']},
    'https://chocolatey.org': {cat:'dl', tags:['Windows']},
    'https://classicjoy.games/zh': {cat:'game', tags:['在线小游戏']},
    'https://claude.ai': {cat:'ai', tags:['对话AI']},
    'https://cn.baozimhcn.com/': {cat:'tools', tags:['tools']},
    'https://cockpit-project.org': {cat:'linux', tags:['服务器']},
    'https://codepen.io': {cat:'dev', tags:['在线工具']},
    'https://console.anthropic.com': {cat:'ai', tags:['开发平台']},
    'https://convertio.co/zh': {cat:'tools', tags:['文件转换']},
    'https://coolors.co': {cat:'tools', tags:['设计资源']},
    'https://dao-fire.com': {cat:'media', tags:['影视下载']},
    'https://deepin.org': {cat:'linux', tags:['发行版']},
    'https://demonoid.se': {cat:'bt', tags:['种子搜索']},
    'https://desk.zol.com.cn': {cat:'tools', tags:['壁纸']},
    'https://developer.mozilla.org': {cat:'dev', tags:['文档参考']},
    'https://dialogue.moe': {cat:'media', tags:['动漫']},
    'https://dict.youdao.com': {cat:'edu', tags:['语言工具']},
    'https://dm84.net/': {cat:'media', tags:['动漫']},
    'https://dmhyy.com/': {cat:'tools', tags:['tools']},
    'https://dribbble.com': {cat:'tools', tags:['设计资源']},
    'https://dtwav.com': {cat:'audio', tags:['无损下载']},
    'https://duzhege.cn': {cat:'read', tags:['小说']},
    'https://dy.qidiandaohang.com': {cat:'media', tags:['网盘搜索']},
    'https://easychuan.cn': {cat:'tools', tags:['文件传输']},
    'https://en.wikipedia.org': {cat:'intl', tags:['英语社区']},
    'https://excalidraw.com': {cat:'tools', tags:['效率协作']},
    'https://explainshell.com': {cat:'linux', tags:['命令行']},
    'https://eztv.ag': {cat:'bt', tags:['种子搜索']},
    'https://f-droid.org': {cat:'mob', tags:['应用商店']},
    'https://fangkong.cc': {cat:'media', tags:['网盘搜索']},
    'https://fcpic.nesbbs.com/game.html': {cat:'game', tags:['模拟器']},
    'https://fitacg.com': {cat:'read', tags:['动漫']},
    'https://flac.life': {cat:'audio', tags:['无损下载']},
    'https://flowith.io/': {cat:'tools', tags:['效率协作']},
    'https://fonts.google.com': {cat:'tools', tags:['设计资源']},
    'https://framegrab.cc/zh': {cat:'tools', tags:['图片处理']},
    'https://gamefaqs.gamespot.com': {cat:'game', tags:['游戏资讯']},
    'https://gaoyuanxia.cn/ying-shi': {cat:'media', tags:['影视下载']},
    'https://gaze.red': {cat:'media', tags:['在线观看']},
    'https://gemini.google.com': {cat:'ai', tags:['对话AI']},
    'https://gitee.com': {cat:'dev', tags:['代码托管']},
    'https://github.com': {cat:'dev', tags:['代码托管']},
    'https://github.com/yt-dlp/yt-dlp': {cat:'dl', tags:['视频下载']},
    'https://gitlab.com': {cat:'dev', tags:['代码托管']},
    'https://gnome.org': {cat:'linux', tags:['桌面环境']},
    'https://godamh.com': {cat:'read', tags:['漫画']},
    'https://godotengine.org': {cat:'game', tags:['游戏开发']},
    'https://haowallpaper.com': {cat:'tools', tags:['壁纸']},
    'https://hatena.ne.jp': {cat:'intl', tags:['日语社区']},
    'https://hdqwalls.com': {cat:'tools', tags:['壁纸']},
    'https://huggingface.co': {cat:'ai', tags:['开发平台']},
    'https://internetdownloadmanager.com': {cat:'dl', tags:['下载管理']},
    'https://itch.io': {cat:'game', tags:['游戏商店']},
    'https://iterm2.com': {cat:'linux', tags:['macOS']},
    'https://jciyuan.com/': {cat:'tools', tags:['tools']},
    'https://jdownloader.org': {cat:'dl', tags:['下载管理']},
    'https://jianyunys.com/': {cat:'tools', tags:['tools']},
    'https://jidi520.com': {cat:'game', tags:['单机资源']},
    'https://jikeshijian.cn': {cat:'dev', tags:['学习教程']},
    'https://juejin.cn': {cat:'dev', tags:['社区问答']},
    'https://juok3.top': {cat:'media', tags:['在线观看']},
    'https://kde.org': {cat:'linux', tags:['桌面环境']},
    'https://komiic.cc': {cat:'read', tags:['漫画']},
    'https://komiic.com/': {cat:'tools', tags:['tools']},
    'https://kuafzys.cn': {cat:'media', tags:['网盘搜索']},
    'https://kzzy.fun': {cat:'media', tags:['网盘搜索']},
    'https://leetcode.com': {cat:'edu', tags:['刷题练习']},
    'https://lemonde.fr': {cat:'intl', tags:['其他语言']},
    'https://libgen.lc': {cat:'read', tags:['电子书']},
    'https://lineageos.org': {cat:'mob', tags:['Android工具']},
    'https://liulishuo.com': {cat:'edu', tags:['语言工具']},
    'https://lookscanned.io/scan': {cat:'tools', tags:['文件转换']},
    'https://lucida.to': {cat:'audio', tags:['无损下载']},
    'https://machinelearningmastery.com': {cat:'ai', tags:['研究资源']},
    'https://majorgeeks.com': {cat:'dl', tags:['Windows']},
    'https://mangadex.org': {cat:'read', tags:['漫画']},
    'https://manhua.idmzj.com/': {cat:'read', tags:['read', '漫画']},
    'https://manhua.sfacg.com/': {cat:'read', tags:['read', '漫画']},
    'https://manwawang.com/': {cat:'tools', tags:['tools']},
    'https://mao.souldebug.com': {cat:'media', tags:['网盘搜索']},
    'https://medium.com': {cat:'intl', tags:['英语社区']},
    'https://mhx12.com/': {cat:'tools', tags:['tools']},
    'https://mifun.tv/': {cat:'media', tags:['动漫']},
    'https://mikanime.tv': {cat:'media', tags:['动漫']},
    'https://msmy.cn': {cat:'media', tags:['网盘搜索']},
    'https://music.163.com': {cat:'audio', tags:['音乐平台']},
    'https://music.apple.com': {cat:'audio', tags:['音乐平台']},
    'https://musopen.org': {cat:'audio', tags:['无损下载']},
    'https://naver.com': {cat:'intl', tags:['韩语社区']},
    'https://news.ycombinator.com': {cat:'intl', tags:['英语社区']},
    'https://ninite.com': {cat:'dl', tags:['Windows']},
    'https://obsidian.md': {cat:'tools', tags:['效率协作']},
    'https://ohmyz.sh': {cat:'linux', tags:['命令行']},
    'https://oldswf.com': {cat:'game', tags:['在线小游戏']},
    'https://oldversion.com': {cat:'dl', tags:['Windows']},
    'https://open.spotify.com': {cat:'audio', tags:['音乐平台']},
    'https://open.spotify.com/browse/podcasts': {cat:'audio', tags:['播客']},
    'https://openlibrary.org': {cat:'read', tags:['电子书']},
    'https://paperpal.cn/': {cat:'tools', tags:['效率协作']},
    'https://paperswithcode.com': {cat:'ai', tags:['研究资源']},
    'https://pcsx2.net': {cat:'game', tags:['模拟器']},
    'https://pexels.com': {cat:'tools', tags:['图片素材']},
    'https://pixabay.com': {cat:'tools', tags:['图片素材']},
    'https://platform.openai.com': {cat:'ai', tags:['开发平台']},
    'https://play.google.com': {cat:'mob', tags:['应用商店']},
    'https://poki.com/zh': {cat:'game', tags:['在线小游戏']},
    'https://pomo.mom': {cat:'bt', tags:['种子搜索']},
    'https://portableapps.com': {cat:'dl', tags:['Windows']},
    'https://qbittorrent.org': {cat:'bt', tags:['BT客户端']},
    'https://quora.com': {cat:'intl', tags:['英语社区']},
    'https://radio.garden': {cat:'audio', tags:['电台']},
    'https://radio5.cn': {cat:'audio', tags:['电台']},
    'https://ray.so': {cat:'tools', tags:['效率协作']},
    'https://reddit.com': {cat:'intl', tags:['英语社区']},
    'https://rejusou.com': {cat:'media', tags:['网盘搜索']},
    'https://retroarch.com': {cat:'game', tags:['模拟器']},
    'https://roadmap.sh': {cat:'dev', tags:['学习教程']},
    'https://runoob.com': {cat:'dev', tags:['学习教程']},
    'https://runwayml.com': {cat:'ai', tags:['AI创作']},
    'https://ryujinx.org': {cat:'game', tags:['模拟器']},
    'https://saucenao.com': {cat:'media', tags:['字幕工具']},
    'https://scholar.google.com': {cat:'edu', tags:['学术研究']},
    'https://shellcheck.net': {cat:'linux', tags:['命令行']},
    'https://sideloadly.io': {cat:'mob', tags:['iOS工具']},
    'https://sidhub.cc': {cat:'bt', tags:['种子搜索']},
    'https://smallpdf.com/cn#r=app': {cat:'tools', tags:['文件转换']},
    'https://snapcraft.io': {cat:'dl', tags:['Mac/Linux']},
    'https://so.252035.xyz': {cat:'media', tags:['网盘搜索']},
    'https://sobooks.cc': {cat:'read', tags:['电子书']},
    'https://soundcloud.com': {cat:'audio', tags:['音乐平台']},
    'https://spiegel.de': {cat:'intl', tags:['其他语言']},
    'https://spline.design': {cat:'tools', tags:['设计资源']},
    'https://squoosh.app': {cat:'tools', tags:['图片处理']},
    'https://stackoverflow.com': {cat:'dev', tags:['社区问答']},
    'https://steamzg.com': {cat:'game', tags:['单机资源']},
    'https://store.steampowered.com': {cat:'game', tags:['游戏商店']},
    'https://subhd.tv': {cat:'media', tags:['字幕工具']},
    'https://suno.com': {cat:'ai', tags:['AI创作']},
    'https://system76.com/pop-os': {cat:'linux', tags:['发行版']},
    'https://t-rex.tzfile.com': {cat:'media', tags:['影视下载']},
    'https://temp-mail.io/zh': {cat:'tools', tags:['隐私安全']},
    'https://tinify.cn': {cat:'tools', tags:['图片处理']},
    'https://tongchuan.iflyrec.com/': {cat:'audio', tags:['音频工具']},
    'https://tools.pdf24.org/zh/all-tools': {cat:'tools', tags:['文件转换']},
    'https://topjohnwu.github.io/Magisk/': {cat:'mob', tags:['Android工具']},
    'https://trace.moe': {cat:'media', tags:['动漫']},
    'https://translate.google.cn': {cat:'edu', tags:['语言工具']},
    'https://transmissionbt.com': {cat:'bt', tags:['BT客户端']},
    'https://ttsmaker.cn': {cat:'audio', tags:['音频工具']},
    'https://tunein.com': {cat:'audio', tags:['电台']},
    'https://tv.garden': {cat:'media', tags:['直播']},
    'https://twrp.me': {cat:'mob', tags:['Android工具']},
    'https://ubuntu.com': {cat:'linux', tags:['发行版']},
    'https://unity.com': {cat:'game', tags:['游戏开发']},
    'https://unsplash.com': {cat:'tools', tags:['图片素材']},
    'https://v.qq.com': {cat:'media', tags:['视频平台']},
    'https://v.xl01.eu.cc': {cat:'media', tags:['在线观看']},
    'https://vercel.com': {cat:'dev', tags:['部署运维']},
    'https://video.ainunu.com': {cat:'media', tags:['影视下载']},
    'https://wallhere.com': {cat:'tools', tags:['壁纸']},
    'https://wallpaperscraft.com': {cat:'tools', tags:['壁纸']},
    'https://webtoons.com': {cat:'read', tags:['漫画']},
    'https://whois.pconline.com.cn': {cat:'tools', tags:['网络工具']},
    'https://wmxz.click': {cat:'media', tags:['网盘搜索']},
    'https://wormhole.app': {cat:'tools', tags:['文件传输']},
    'https://wuxianbook.com': {cat:'read', tags:['电子书']},
    'https://www.24bit.net': {cat:'audio', tags:['无损下载']},
    'https://www.2dwallpapers.com': {cat:'tools', tags:['壁纸']},
    'https://www.airportal.cn': {cat:'tools', tags:['文件传输']},
    'https://www.apkmirror.com': {cat:'mob', tags:['应用商店']},
    'https://www.bilibili.com': {cat:'media', tags:['视频平台']},
    'https://www.bttwo.me/': {cat:'bt', tags:['bt']},
    'https://www.cilixiong.org': {cat:'bt', tags:['种子搜索']},
    'https://www.cilixiong.xyz/': {cat:'tools', tags:['tools']},
    'https://www.cloudflare.com': {cat:'dev', tags:['部署运维']},
    'https://www.coursera.org': {cat:'edu', tags:['在线课程']},
    'https://www.crazygames.com': {cat:'game', tags:['在线小游戏']},
    'https://www.creative-comic.tw/zh/': {cat:'read', tags:['read']},
    'https://www.crunchyroll.com': {cat:'media', tags:['视频平台']},
    'https://www.cycdm01.top/': {cat:'media', tags:['动漫']},
    'https://www.cz4k.com': {cat:'media', tags:['在线观看']},
    'https://www.daoso.cn': {cat:'media', tags:['网盘搜索']},
    'https://www.dashumanhua.com/': {cat:'read', tags:['read', '漫画']},
    'https://www.deepl.com/zh/translator': {cat:'edu', tags:['语言工具']},
    'https://www.discogs.com': {cat:'audio', tags:['音乐社区']},
    'https://www.dm5.com/': {cat:'tools', tags:['tools']},
    'https://www.doubao.com/chat/': {cat:'ai', tags:['对话AI']},
    'https://www.douyin.com': {cat:'media', tags:['视频平台']},
    'https://www.duse1.com/': {cat:'tools', tags:['tools']},
    'https://www.dygod.net': {cat:'media', tags:['影视下载']},
    'https://www.edx.org': {cat:'edu', tags:['在线课程']},
    'https://www.epicgames.com': {cat:'game', tags:['游戏商店']},
    'https://www.ezdmw.site/': {cat:'tools', tags:['tools']},
    'https://www.fanchawu.cc/': {cat:'tools', tags:['tools']},
    'https://www.fanxinzhui.com': {cat:'media', tags:['网盘搜索']},
    'https://www.figma.com': {cat:'tools', tags:['设计资源']},
    'https://www.freecodecamp.org': {cat:'edu', tags:['在线课程']},
    'https://www.fsdm02.com': {cat:'media', tags:['动漫']},
    'https://www.gog.com': {cat:'game', tags:['游戏商店']},
    'https://www.gufengmh.com/': {cat:'tools', tags:['tools']},
    'https://www.gutenberg.org': {cat:'read', tags:['电子书']},
    'https://www.hdzu.cc': {cat:'media', tags:['影视下载']},
    'https://www.hisoman.com/': {cat:'tools', tags:['tools']},
    'https://www.humblebundle.com': {cat:'game', tags:['游戏商店']},
    'https://www.icourse163.org': {cat:'edu', tags:['在线课程']},
    'https://www.ign.com': {cat:'game', tags:['游戏资讯']},
    'https://www.imdb.com': {cat:'media', tags:['资讯']},
    'https://www.iqiyi.com': {cat:'media', tags:['视频平台']},
    'https://www.jjsou.com': {cat:'media', tags:['网盘搜索']},
    'https://www.json.cn': {cat:'dev', tags:['在线工具']},
    'https://www.juhebd.com': {cat:'media', tags:['影视下载']},
    'https://www.kanman.com/': {cat:'tools', tags:['tools']},
    'https://www.khanacademy.org': {cat:'edu', tags:['在线课程']},
    'https://www.last.fm': {cat:'audio', tags:['音乐社区']},
    'https://www.libvio.link/': {cat:'tools', tags:['tools']},
    'https://www.libvio.mov': {cat:'media', tags:['在线观看']},
    'https://www.manben.com/': {cat:'tools', tags:['tools']},
    'https://www.mangacopy.com/': {cat:'read', tags:['read', '漫画']},
    'https://www.manhuagou.net/': {cat:'read', tags:['read', '漫画']},
    'https://www.mfgalleria.com/': {cat:'tools', tags:['tools']},
    'https://www.mgtv.com': {cat:'media', tags:['视频平台']},
    'https://www.midjourney.com': {cat:'ai', tags:['AI绘图']},
    'https://www.mjf2020.com': {cat:'media', tags:['影视下载']},
    'https://www.notion.so': {cat:'tools', tags:['效率协作']},
    'https://www.novipnoad.uk': {cat:'media', tags:['在线观看']},
    'https://www.npmjs.com': {cat:'dev', tags:['文档参考']},
    'https://www.onlinegdb.com': {cat:'dev', tags:['在线工具']},
    'https://www.oschina.net': {cat:'dev', tags:['社区问答']},
    'https://www.perplexity.ai': {cat:'ai', tags:['AI搜索']},
    'https://www.remove.bg': {cat:'tools', tags:['图片处理']},
    'https://www.royalroad.com': {cat:'read', tags:['小说']},
    'https://www.rrdynb.com/index.html': {cat:'media', tags:['网盘搜索']},
    'https://www.showpaw.xyz': {cat:'media', tags:['网盘搜索']},
    'https://www.softpedia.com': {cat:'dl', tags:['Windows']},
    'https://www.thepaper.cn': {cat:'media', tags:['资讯']},
    'https://www.theverge.com': {cat:'intl', tags:['英文媒体']},
    'https://www.tvso.uk': {cat:'media', tags:['网盘搜索']},
    'https://www.uniontech.com': {cat:'linux', tags:['发行版']},
    'https://www.wattpad.com': {cat:'read', tags:['小说']},
    'https://www.webnovel.com': {cat:'read', tags:['小说']},
    'https://www.xiguadh.com': {cat:'media', tags:['在线观看']},
    'https://www.ximalaya.com': {cat:'read', tags:['有声书']},
    'https://www.xl720.com': {cat:'media', tags:['影视下载']},
    'https://www.xn--ykq321c.com': {cat:'media', tags:['影视下载']},
    'https://www.ymvid.com/': {cat:'media', tags:['动漫']},
    'https://www.yymanhua.com/': {cat:'read', tags:['read', '漫画']},
    'https://www.zcool.com.cn': {cat:'tools', tags:['设计资源']},
    'https://www.zhihu.com': {cat:'edu', tags:['知识问答']},
    'https://xda-developers.com': {cat:'mob', tags:['Android工具']},
    'https://xueshu.baidu.com': {cat:'edu', tags:['学术研究']},
    'https://xx01.xiguatv.xyz/': {cat:'media', tags:['media']},
    'https://yinghezhinan.com/site/vipshipinjiexi/': {cat:'media', tags:['字幕工具']},
    'https://yingshi.co': {cat:'media', tags:['网盘搜索']},
    'https://yts.mx': {cat:'bt', tags:['种子搜索']},
    'https://yun2s2lxsduo22.top/': {cat:'tools', tags:['tools']},
    'https://yunduoyingshi.com': {cat:'media', tags:['在线观看']},
    'https://yyets.click/search': {cat:'media', tags:['影视下载']},
    'https://z-lib.org': {cat:'read', tags:['电子书']},
    'https://zh.wikipedia.org': {cat:'edu', tags:['知识问答']},
    'https://zlys9.top': {cat:'media', tags:['在线观看']},
    'https://znys.top/': {cat:'tools', tags:['tools']},
  },

  // ── 4. 默认归类（无任何规则匹配时） ──
  default: { cat: 'tools', tags: ['其他'] },
};

// 启动时由 main.js 调用 applyConfig() 合并到 SITES