// ════════════════════════════════════════════════════════
// FLUX · data.js — 站点基础信息（id / name / url / desc / badge）
// 分类信息见 config.js
// ════════════════════════════════════════════════════════

const SITES = [
  {id:'chat-openai-com',name:'ChatGPT',url:'https://chat.openai.com',desc:'OpenAI 出品，GPT-4o 驱动，写作/编程/分析全能。',badge:'hot'},
  {id:'claude-ai',name:'Claude',url:'https://claude.ai',desc:'Anthropic 出品，逻辑严谨，擅长长文与文件分析。',badge:'hot'},
  {id:'gemini-google-com',name:'Gemini',url:'https://gemini.google.com',desc:'Google 多模态 AI，深度整合搜索与 Workspace 生态。'},
  {id:'perplexity-ai',name:'Perplexity',url:'https://www.perplexity.ai',desc:'AI 搜索引擎，实时联网并附来源引用。',badge:'new'},
  {id:'doubao-com-chat',name:'豆包',url:'https://www.doubao.com/chat/',desc:'字节跳动出品的 AI 对话助手，中文体验优秀。',badge:'cn'},
  {id:'midjourney-com',name:'Midjourney',url:'https://www.midjourney.com',desc:'顶级 AI 图像生成，艺术风格出众，支持 Web 端。'},
  {id:'suno-com',name:'Suno',url:'https://suno.com',desc:'AI 音乐生成，输入描述即可生成完整歌曲。',badge:'new'},
  {id:'runwayml-com',name:'Runway',url:'https://runwayml.com',desc:'AI 视频生成与编辑平台，Gen-3 支持文字/图片转视频。'},
  {id:'huggingface-co',name:'Hugging Face',url:'https://huggingface.co',desc:'机器学习模型与数据集托管平台，开源 AI 核心社区。'},
  {id:'platform-openai-com',name:'OpenAI Platform',url:'https://platform.openai.com',desc:'OpenAI API 控制台，接入 GPT-4o 等模型构建应用。'},
  {id:'aistudio-google-com',name:'Google AI Studio',url:'https://aistudio.google.com',desc:'Google Gemini API 调试与原型工具，免费额度高。'},
  {id:'console-anthropic-com',name:'Claude API',url:'https://console.anthropic.com',desc:'Anthropic API 控制台，Claude 模型测试与调用。'},
  {id:'paperswithcode-com',name:'Papers with Code',url:'https://paperswithcode.com',desc:'最新 AI 论文与开源代码一站式查阅。'},
  {id:'machinelearningmastery-com',name:'ML Mastery',url:'https://machinelearningmastery.com',desc:'ML 实战教程网站，从入门到进阶学习。'},
  {id:'github-com',name:'GitHub',url:'https://github.com',desc:'全球最大代码托管与开源协作平台，Copilot AI 辅助编程。'},
  {id:'gitlab-com',name:'GitLab',url:'https://gitlab.com',desc:'企业级 DevOps 平台，支持私有部署与 CI/CD 流水线。'},
  {id:'gitee-com',name:'Gitee 码云',url:'https://gitee.com',desc:'国内主流代码托管平台，速度快，对中文友好。',badge:'cn'},
  {id:'stackoverflow-com',name:'Stack Overflow',url:'https://stackoverflow.com',desc:'程序员问答社区，几乎所有技术问题都有解答。'},
  {id:'juejin-cn',name:'掘金',url:'https://juejin.cn',desc:'面向开发者的技术社区，前端/后端/AI 内容丰富。',badge:'cn'},
  {id:'developer-mozilla-org',name:'MDN Web Docs',url:'https://developer.mozilla.org',desc:'HTML/CSS/JS 权威参考文档，前端必备手册。'},
  {id:'runoob-com',name:'菜鸟教程',url:'https://runoob.com',desc:'全中文编程入门教程，覆盖几乎所有主流语言。',badge:'cn'},
  {id:'jikeshijian-cn',name:'极客时间',url:'https://jikeshijian.cn',desc:'付费技术专栏平台，大厂工程师出品，质量高。',badge:'cn'},
  {id:'vercel-com',name:'Vercel',url:'https://vercel.com',desc:'前端云部署平台，Git 推送自动部署，Next.js 官方支持。'},
  {id:'cloudflare-com',name:'Cloudflare',url:'https://www.cloudflare.com',desc:'CDN、DNS、安全与边缘计算平台，免费套餐极具价值。'},
  {id:'codepen-io',name:'CodePen',url:'https://codepen.io',desc:'在线 HTML/CSS/JS 编辑器，前端灵感分享社区。',badge:'free'},
  {id:'json-cn',name:'JSON 格式化',url:'https://www.json.cn',desc:'在线 JSON 格式化、压缩、校验工具。',badge:'free'},
  {id:'onlinegdb-com',name:'在线 GDB',url:'https://www.onlinegdb.com',desc:'多语言在线代码编辑与运行调试环境。',badge:'free'},
  {id:'roadmap-sh',name:'roadmap.sh',url:'https://roadmap.sh',desc:'前端/后端/DevOps 等方向可视化学习路线图。',badge:'free'},
  {id:'oschina-net',name:'OSCHINA',url:'https://www.oschina.net',desc:'中文开源社区，发现国内开源项目与资讯。',badge:'cn'},
  {id:'npmjs-com',name:'npm',url:'https://www.npmjs.com',desc:'Node.js 包管理中心，搜索查询 200 万+ JS 包。'},
  {id:'icourse163-org',name:'中国大学MOOC',url:'https://www.icourse163.org',desc:'顶尖高校精品课程在线平台，国家级认证证书。',badge:'cn'},
  {id:'coursera-org',name:'Coursera',url:'https://www.coursera.org',desc:'与全球顶尖大学合作的国际在线课程，部分可免费审计。'},
  {id:'edx-org',name:'edX',url:'https://www.edx.org',desc:'MIT、哈佛等名校开放课程，提供认证证书。'},
  {id:'khanacademy-org',name:'Khan Academy',url:'https://www.khanacademy.org',desc:'免费优质基础学科辅导，从小学到大学全覆盖。',badge:'free'},
  {id:'freecodecamp-org',name:'freeCodeCamp',url:'https://www.freecodecamp.org',desc:'免费学编程，Web/Python/数据科学课程完整体系。',badge:'free'},
  {id:'leetcode-com',name:'LeetCode',url:'https://leetcode.com',desc:'算法与数据结构刷题平台，面试备考必备。'},
  {id:'scholar-google-com',name:'谷歌学术',url:'https://scholar.google.com',desc:'学术论文搜索引擎，覆盖各学科顶刊文献。'},
  {id:'xueshu-baidu-com',name:'百度学术',url:'https://xueshu.baidu.com',desc:'中文学术搜索，收录大量中文期刊与论文。',badge:'cn'},
  {id:'zhihu-com',name:'知乎',url:'https://www.zhihu.com',desc:'中文知识问答社区，高质量专业内容聚集地。',badge:'cn'},
  {id:'zh-wikipedia-org',name:'维基百科',url:'https://zh.wikipedia.org',desc:'全球最大开放百科全书，中文版持续更新。',badge:'free'},
  {id:'deepl-com-zh-translator',name:'DeepL',url:'https://www.deepl.com/zh/translator',desc:'精度最高的 AI 翻译服务，支持多种语言对。'},
  {id:'dict-youdao-com',name:'有道词典',url:'https://dict.youdao.com',desc:'网易出品专业词典，支持例句、发音与专业词汇。',badge:'cn'},
  {id:'liulishuo-com',name:'英语流利说',url:'https://liulishuo.com',desc:'AI 口语教练，自适应训练提升英语口语。',badge:'cn'},
  {id:'translate-google-cn',name:'谷歌翻译',url:'https://translate.google.cn',desc:'Google 翻译国内镜像，覆盖 100+ 语言。',badge:'free'},
  {id:'notion-so',name:'Notion',url:'https://www.notion.so',desc:'全能型笔记与协作工具，支持数据库、看板，AI 写作。'},
  {id:'obsidian-md',name:'Obsidian',url:'https://obsidian.md',desc:'本地优先知识管理，双向链接图谱，强大插件生态。',badge:'free'},
  {id:'excalidraw-com',name:'Excalidraw',url:'https://excalidraw.com',desc:'手绘风格白板，实时协作，适合架构图与头脑风暴。',badge:'free'},
  {id:'ray-so',name:'Ray.so',url:'https://ray.so',desc:'将代码片段生成精美截图，分享代码必备工具。',badge:'free'},
  {id:'flowith-io',name:'Flowith',url:'https://flowith.io/',desc:'AI 驱动的流式思维导图与写作工具。',badge:'new'},
  {id:'paperpal-cn',name:'Paperpal',url:'https://paperpal.cn/',desc:'AI 学术论文写作辅助，润色检查一体化。'},
  {id:'unsplash-com',name:'Unsplash',url:'https://unsplash.com',desc:'百万张高清摄影图免费商用，无需授权。',badge:'free'},
  {id:'pexels-com',name:'Pexels',url:'https://pexels.com',desc:'免费企业级高清图片与视频，商用授权友好。',badge:'free'},
  {id:'pixabay-com',name:'Pixabay',url:'https://pixabay.com',desc:'免费图片、插画、视频素材库，覆盖面广。',badge:'free'},
  {id:'netbian-com',name:'彼岸壁纸',url:'http://www.netbian.com',desc:'国内老牌壁纸站，高清图片资源丰富。',badge:'cn'},
  {id:'wallhere-com',name:'Wallhere',url:'https://wallhere.com',desc:'高质量壁纸收藏分享站，风格多样。',badge:'free'},
  {id:'wallpaperscraft-com',name:'WallpapersCraft',url:'https://wallpaperscraft.com',desc:'精美高清壁纸免费下载，支持多种分辨率。',badge:'free'},
  {id:'hdqwalls-com',name:'HDQwalls',url:'https://hdqwalls.com',desc:'4K 超清壁纸下载，游戏/电影/自然主题丰富。',badge:'free'},
  {id:'2dwallpapers-com',name:'2DWallpapers',url:'https://www.2dwallpapers.com',desc:'动漫/二次元风格壁纸专属下载站。',badge:'free'},
  {id:'desk-zol-com-cn',name:'ZOL壁纸',url:'https://desk.zol.com.cn',desc:'中关村在线旗下壁纸站，PC/手机壁纸海量收录。',badge:'cn'},
  {id:'haowallpaper-com',name:'好壁纸',url:'https://haowallpaper.com',desc:'精选好看高清壁纸，风景/人像/动漫全覆盖。',badge:'cn'},
  {id:'dribbble-com',name:'Dribbble',url:'https://dribbble.com',desc:'顶级 UI/UX 设计师作品展示社区与招募平台。'},
  {id:'zcool-com-cn',name:'站酷',url:'https://www.zcool.com.cn',desc:'国内最大设计师社区，作品展示与素材下载。',badge:'cn'},
  {id:'figma-com',name:'Figma',url:'https://www.figma.com',desc:'协作式 UI/UX 设计工具，实时多人编辑，行业标准。'},
  {id:'coolors-co',name:'Coolors',url:'https://coolors.co',desc:'快速生成配色方案，支持锁定颜色继续生成。',badge:'free'},
  {id:'fonts-google-com',name:'Google Fonts',url:'https://fonts.google.com',desc:'1500+ 开源字体库，免费商用，CDN 直接引用。',badge:'free'},
  {id:'spline-design',name:'Spline',url:'https://spline.design',desc:'浏览器端 3D 设计工具，可导出可交互 3D 网页组件。',badge:'new'},
  {id:'remove-bg',name:'Remove.bg',url:'https://www.remove.bg',desc:'AI 一键抠图，自动去除图片背景，精度极高。'},
  {id:'squoosh-app',name:'Squoosh',url:'https://squoosh.app',desc:'Google 出品在线图片压缩，支持 WebP 等多格式。',badge:'free'},
  {id:'tinify-cn',name:'TinyPNG',url:'https://tinify.cn',desc:'PNG/JPG 在线智能压缩，图质量几乎无损。',badge:'free'},
  {id:'bigjpg-com',name:'Bigjpg',url:'https://bigjpg.com',desc:'AI 超分辨率图片放大，无损扩大图片尺寸。',badge:'free'},
  {id:'framegrab-cc-zh',name:'FrameGrab',url:'https://framegrab.cc/zh',desc:'从视频中精准截取高清帧图片。',badge:'free'},
  {id:'convertio-co-zh',name:'Convertio',url:'https://convertio.co/zh',desc:'在线文件格式转换，支持 300+ 种格式。'},
  {id:'smallpdf-com-cn',name:'Smallpdf',url:'https://smallpdf.com/cn#r=app',desc:'PDF 工具集合：合并、拆分、压缩、转换一站搞定。'},
  {id:'tools-pdf24-org-zh-all-tools',name:'PDF24',url:'https://tools.pdf24.org/zh/all-tools',desc:'全套 PDF 工具，免费无水印，支持本地处理。',badge:'free'},
  {id:'lookscanned-io-scan',name:'Look Scanned',url:'https://lookscanned.io/scan',desc:'让 PDF 看起来像扫描件，隐私安全本地处理。',badge:'free'},
  {id:'temp-mail-io-zh',name:'临时邮箱',url:'https://temp-mail.io/zh',desc:'一次性临时邮箱，保护隐私、防止垃圾邮件。',badge:'free'},
  {id:'bitwarden-com',name:'Bitwarden',url:'https://bitwarden.com',desc:'开源密码管理器，端对端加密，支持全平台同步。',badge:'free'},
  {id:'airportal-cn',name:'AirPortal',url:'https://www.airportal.cn',desc:'极简文件传输，无需登录，局域网与公网均可。',badge:'free'},
  {id:'wormhole-app',name:'WormHole',url:'https://wormhole.app',desc:'加密临时文件传输，最大 5GB，链接自动过期。',badge:'free'},
  {id:'easychuan-cn',name:'EasyChuan',url:'https://easychuan.cn',desc:'简洁易用的局域网文件传输工具，无需安装。',badge:'free'},
  {id:'whois-pconline-com-cn',name:'IP 查询',url:'https://whois.pconline.com.cn',desc:'查询本机或任意 IP 的地理位置与运营商信息。',badge:'free'},
  {id:'gutenberg-org',name:'Project Gutenberg',url:'https://www.gutenberg.org',desc:'60,000+ 免费公版电子书，可合法下载使用。',badge:'free'},
  {id:'z-lib-org',name:'Z-Library',url:'https://z-lib.org',desc:'全球最大电子书图书馆，覆盖数百万本书籍。'},
  {id:'libgen-lc',name:'LibGen',url:'https://libgen.lc',desc:'学术书籍与论文下载，科研工作者常用资源。'},
  {id:'sobooks-cc',name:'SoBooks',url:'https://sobooks.cc',desc:'中文电子书免费下载，以文学与人文类为主。',badge:'free'},
  {id:'wuxianbook-com',name:'无限书',url:'https://wuxianbook.com',desc:'中文电子书资源站，小说/教材/人文类丰富。',badge:'free'},
  {id:'502book-com',name:'502Book',url:'https://502book.com',desc:'免费电子书下载，格式多样，覆盖面广。',badge:'free'},
  {id:'openlibrary-org',name:'Open Library',url:'https://openlibrary.org',desc:'互联网档案馆旗下开放图书馆，可在线借阅。',badge:'free'},
  {id:'books-google-com',name:'Google Books',url:'https://books.google.com',desc:'谷歌图书搜索，可预览部分书籍正文内容。'},
  {id:'audiobookbay-lu',name:'AudiobookBay',url:'https://audiobookbay.lu',desc:'英文有声书下载站，资源海量免费。',badge:'free'},
  {id:'ximalaya-com',name:'喜马拉雅',url:'https://www.ximalaya.com',desc:'国内最大音频内容平台，有声书/播客全覆盖。',badge:'cn'},
  {id:'mangadex-org',name:'MangaDex',url:'https://mangadex.org',desc:'最大在线漫画平台，多语言翻译版本。'},
  {id:'komiic-cc',name:'Komiic',url:'https://komiic.cc',desc:'高质量漫画在线阅读平台，更新及时。',badge:'free'},
  {id:'godamh-com',name:'GodaMH',url:'https://godamh.com',desc:'免费漫画在线阅读，资源覆盖广。',badge:'free'},
  {id:'webtoons-com',name:'Webtoons',url:'https://webtoons.com',desc:'韩漫（Webtoon）官方平台，全球最大数字漫画。'},
  {id:'wattpad-com',name:'Wattpad',url:'https://www.wattpad.com',desc:'全球最大在线写作与阅读社区，网文平台。'},
  {id:'webnovel-com',name:'Webnovel',url:'https://www.webnovel.com',desc:'起点国际版，中国网络小说英译平台。'},
  {id:'royalroad-com',name:'Royal Road',url:'https://www.royalroad.com',desc:'英文网络小说社区，西方奇幻题材丰富。',badge:'free'},
  {id:'archiveofourown-org',name:'Archive of Our Own',url:'https://archiveofourown.org',desc:'全球最大同人创作社区（AO3），覆盖各大 IP。'},
  {id:'duzhege-cn',name:'独者阁',url:'https://duzhege.cn',desc:'精品中文电子书分享社区，质量有保证。',badge:'free'},
  {id:'bangumi-tv',name:'Bangumi',url:'https://bangumi.tv',desc:'动画、漫画、游戏综合评分与收藏数据库，二次元圣地。',badge:'cn'},
  {id:'bgmlist-com',name:'BGMList',url:'https://bgmlist.com',desc:'番剧放送列表，每季新番一览无余。',badge:'free'},
  {id:'fitacg-com',name:'FitACG',url:'https://fitacg.com',desc:'ACG 综合资源站，动漫/游戏/音乐全覆盖。',badge:'free'},
  {id:'bilibili-com',name:'Bilibili',url:'https://www.bilibili.com',desc:'国内最大二次元视频平台，也是知识/科技内容聚集地。',badge:'cn'},
  {id:'v-qq-com',name:'腾讯视频',url:'https://v.qq.com',desc:'国内领先长视频平台，覆盖影视剧与综艺。',badge:'cn'},
  {id:'iqiyi-com',name:'爱奇艺',url:'https://www.iqiyi.com',desc:'优质剧综会员视频平台，独播内容丰富。',badge:'cn'},
  {id:'mgtv-com',name:'芒果TV',url:'https://www.mgtv.com',desc:'湖南卫视旗下综艺与剧集平台。',badge:'cn'},
  {id:'crunchyroll-com',name:'Crunchyroll',url:'https://www.crunchyroll.com',desc:'全球最大正版动漫流媒体，海量日漫资源。'},
  {id:'douyin-com',name:'抖音',url:'https://www.douyin.com',desc:'字节跳动旗下短视频平台，兴趣内容推荐。',badge:'cn'},
  {id:'yunduoyingshi-com',name:'云朵影视',url:'https://yunduoyingshi.com',desc:'影视剧高清在线观看，线路稳定清晰。',badge:'free'},
  {id:'gaze-red',name:'注视影视',url:'https://gaze.red',desc:'海外影视剧为主，国内高口碑剧集俱备的在线影视站。',badge:'free'},
  {id:'novipnoad-uk',name:'No视频',url:'https://www.novipnoad.uk',desc:'主打海外影视剧资源，追剧体验轻松流畅。',badge:'free'},
  {id:'juok3-top',name:'剧OK',url:'https://juok3.top',desc:'可观看全网影视剧的在线追剧网站。',badge:'free'},
  {id:'zlys9-top',name:'真狼影视',url:'https://zlys9.top',desc:'免费观看全网影视剧资源的网站。',badge:'free'},
  {id:'v-xl01-eu-cc',name:'雪落影视',url:'https://v.xl01.eu.cc',desc:'原修罗影视，内容丰富的综合型老牌优质影视站。',badge:'free'},
  {id:'xiguadh-com',name:'西瓜影院',url:'https://www.xiguadh.com',desc:'免费在线观看全网高清影视剧的综合型网站。',badge:'free'},
  {id:'libvio-mov',name:'LIBVIO',url:'https://www.libvio.mov',desc:'以海外影视资源为主的老牌网站，画质优秀。',badge:'free'},
  {id:'cz4k-com',name:'厂长资源',url:'https://www.cz4k.com',desc:'高清秒播不卡顿的综合型影视资源网站。',badge:'free'},
  {id:'anime1-me',name:'Anime1',url:'https://anime1.me',desc:'台湾动漫在线观看网站，支持国语/日语双轨。',badge:'free'},
  {id:'mikanime-tv',name:'Mikan 蜜柑',url:'https://mikanime.tv',desc:'动漫 BT 资源聚合站，字幕组作品集中收录。',badge:'free'},
  {id:'ani-pekolove-net',name:'Ani动漫',url:'https://ani.pekolove.net',desc:'动漫在线观看站，资源覆盖广。',badge:'free'},
  {id:'trace-moe',name:'Trace.moe',url:'https://trace.moe',desc:'通过截图反向搜索动漫来源，精准定位番剧集数。',badge:'free'},
  {id:'dm84-net',name:'动漫巴士',url:'https://dm84.net/',desc:'主打动漫在线观看，备用域名dm84.vip/dm84.pro，发布页dmbus.cc。',badge:'free'},
  {id:'mifun-tv',name:'MiFun',url:'https://mifun.tv/',desc:'动漫视频App，官网www.huai-de.com，开发方贵阳混鑫科技有限公司。',badge:'free'},
  {id:'ymvid-com',name:'粤漫之家',url:'https://www.ymvid.com/',desc:'主打粤语配音动漫的App，粤语动漫资源丰富。',badge:'free'},
  {id:'fsdm02-com',name:'番薯动漫',url:'https://www.fsdm02.com',desc:'备用域名fsdm01.com/fanshudm.cc/fanshudm.com，发布页fsdm.top。',badge:'free'},
  {id:'cycdm01-top',name:'次元城动画',url:'https://www.cycdm01.top/',desc:'动漫在线观看网站。',badge:'free'},
  {id:'dialogue-moe',name:'Dialogue.moe',url:'https://dialogue.moe',desc:'通过动漫台词搜索具体出处，二次元必备。',badge:'free'},
  {id:'xn--ykq321c-com',name:'GYing 观影',url:'https://www.xn--ykq321c.com',desc:'观影GYing/片库网，老牌影视资源名站。',badge:'free'},
  {id:'juhebd-com',name:'BD影视',url:'https://www.juhebd.com',desc:'支持迅雷、网盘下载的 4K 影视分享网站。',badge:'free'},
  {id:'video-ainunu-com',name:'爱努努',url:'https://video.ainunu.com',desc:'分享各种主流网盘资源的老牌资源站点。',badge:'free'},
  {id:'hdzu-cc',name:'高清族',url:'https://www.hdzu.cc',desc:'提供 4K/1080/720 多版本资源的高清影视下载站。',badge:'free'},
  {id:'xl720-com',name:'迅雷电影天堂',url:'https://www.xl720.com',desc:'高清迅雷电影、电视剧下载老牌网站。',badge:'free'},
  {id:'dygod-net',name:'电影天堂',url:'https://www.dygod.net',desc:'专业老牌迅雷影视下载站，更新及时。',badge:'free'},
  {id:'mjf2020-com',name:'美剧粉',url:'https://www.mjf2020.com',desc:'专业美剧、Netflix 资源下载网站，更新及时。',badge:'free'},
  {id:'yyets-click-search',name:'人人影视站',url:'https://yyets.click/search',desc:'包含人人影视字幕组资源的分享网站。',badge:'free'},
  {id:'t-rex-tzfile-com',name:'团长资源',url:'https://t-rex.tzfile.com',desc:'霸王龙压制组，提供主流网盘下载的知名影视分享站。',badge:'free'},
  {id:'dao-fire-com',name:'全球纪录片库',url:'https://dao-fire.com',desc:'提供全球纪录片下载的资源网站，内容丰富。',badge:'free'},
  {id:'gaoyuanxia-cn-ying-shi',name:'高原下',url:'https://gaoyuanxia.cn/ying-shi',desc:'提供影片、电子书、游戏等资源的综合下载网站。',badge:'free'},
  {id:'rrdynb-com-index-html',name:'人人电影',url:'https://www.rrdynb.com/index.html',desc:'夸克、百度、迅雷、UC 等多网盘资源搜索站。',badge:'free'},
  {id:'so-252035-xyz',name:'盘搜',url:'https://so.252035.xyz',desc:'支持搜索夸克、百度、迅雷、UC 等 10+ 网盘资源。',badge:'free'},
  {id:'showpaw-xyz',name:'Showpaw',url:'https://www.showpaw.xyz',desc:'支持百度、夸克、115 等主流网盘的一站式影视搜索。',badge:'free'},
  {id:'yingshi-co',name:'影视搜',url:'https://yingshi.co',desc:'以夸克、百度网盘为主的影视资源搜索网站。',badge:'free'},
  {id:'kzzy-fun',name:'库库光影',url:'https://kzzy.fun',desc:'夸克、迅雷、百度、UC、天翼、115 多平台影片搜索。',badge:'free'},
  {id:'5kep-top',name:'吾可盘',url:'https://5kep.top',desc:'夸克、百度、迅雷、UC 为主的多网盘搜索网站。',badge:'free'},
  {id:'wmxz-click',name:'无名小卒',url:'https://wmxz.click',desc:'支持夸克、百度、UC 为主的网盘资源搜索引擎。',badge:'free'},
  {id:'rejusou-com',name:'热剧搜索',url:'https://rejusou.com',desc:'以夸克网盘为主的网盘影视搜索引擎。',badge:'free'},
  {id:'mao-souldebug-com',name:'肥猫追剧',url:'https://mao.souldebug.com',desc:'短剧、电视剧、动漫综艺的夸克网盘资源分享站。',badge:'free'},
  {id:'dy-qidiandaohang-com',name:'奇点追剧',url:'https://dy.qidiandaohang.com',desc:'夸克网盘、百度网盘资源为主的影视搜索平台。',badge:'free'},
  {id:'msmy-cn',name:'妙搜云',url:'https://msmy.cn',desc:'支持国内各大网盘的资源搜索引擎。',badge:'free'},
  {id:'daoso-cn',name:'刀搜盘',url:'https://www.daoso.cn',desc:'提供百度、迅雷网盘资源的搜索站。',badge:'free'},
  {id:'kuafzys-cn',name:'夸父资源',url:'https://kuafzys.cn',desc:'夸克网盘为主的影视资源分享社区。',badge:'free'},
  {id:'akongwu-com',name:'A控屋',url:'https://akongwu.com',desc:'恐怖电影资源分享为主，夸克网盘资源丰富。',badge:'free'},
  {id:'tvso-uk',name:'TV搜',url:'https://www.tvso.uk',desc:'夸克网盘影视搜索，TV 资源丰富。',badge:'free'},
  {id:'j-so-com',name:'珈珈4K网盘',url:'http://j-so.com',desc:'以百度、夸克、迅雷、阿里、UC 为主的影片网盘搜索。',badge:'free'},
  {id:'fanxinzhui-com',name:'追新番',url:'https://www.fanxinzhui.com',desc:'专注日本影视剧的腾讯微云网盘资源分享网站。',badge:'free'},
  {id:'fangkong-cc',name:'放空一夏',url:'https://fangkong.cc',desc:'主打广播剧、有声剧的夸克资源网站。',badge:'free'},
  {id:'jjsou-com',name:'JJ搜',url:'https://www.jjsou.com',desc:'夸克、百度、UC 网盘资源搜索站。',badge:'free'},
  {id:'assrt-net',name:'字幕库ASSRT',url:'https://assrt.net',desc:'老牌中文字幕下载站，收录海量影视字幕资源。',badge:'free'},
  {id:'subhd-tv',name:'SubHD',url:'https://subhd.tv',desc:'高质量中文字幕下载网站，更新及时。',badge:'free'},
  {id:'33-agilestudio-cn',name:'33台词',url:'https://33.agilestudio.cn',desc:'通过台词找到影片，还可进行二次加工创作。',badge:'free'},
  {id:'saucenao-com',name:'SauceNAO',url:'https://saucenao.com',desc:'以图搜图，快速找到动漫/插画的原始来源。',badge:'free'},
  {id:'yinghezhinan-com-site-vipshipinjiexi',name:'VIP视频解析',url:'https://yinghezhinan.com/site/vipshipinjiexi/',desc:'免 VIP 观看全网付费影片的解析接口合集。',badge:'free'},
  {id:'tv-garden',name:'神器TV',url:'https://tv.garden',desc:'在线免费电视直播，覆盖各大卫视频道。',badge:'free'},
  {id:'thepaper-cn',name:'澎湃新闻',url:'https://www.thepaper.cn',desc:'深度报道与调查新闻媒体，优质中文资讯。',badge:'cn'},
  {id:'imdb-com',name:'IMDb',url:'https://www.imdb.com',desc:'全球最权威电影数据库，评分与演职员信息。'},
  {id:'open-spotify-com',name:'Spotify',url:'https://open.spotify.com',desc:'全球最大音乐流媒体，8000 万+ 歌曲，播客丰富。'},
  {id:'music-apple-com',name:'Apple Music',url:'https://music.apple.com',desc:'苹果音乐服务，无损音质，与 Apple 生态深度融合。'},
  {id:'music-163-com',name:'网易云音乐',url:'https://music.163.com',desc:'国内最大音乐社区，歌单与乐评生态完善。',badge:'cn'},
  {id:'soundcloud-com',name:'SoundCloud',url:'https://soundcloud.com',desc:'独立音乐人分享与发现社区，先锋音乐聚集地。'},
  {id:'bandcamp-com',name:'Bandcamp',url:'https://bandcamp.com',desc:'支持独立音乐人的付费音乐平台，品质保证。'},
  {id:'lucida-to',name:'Lucida',url:'https://lucida.to',desc:'多平台无损音乐下载工具，一站解决听歌下歌需求。',badge:'free'},
  {id:'flac-life',name:'FLAC.Life',url:'https://flac.life',desc:'无损 FLAC 音乐下载站，Hi-Res 音乐资源丰富。',badge:'free'},
  {id:'24bit-net',name:'24BIT 无损',url:'https://www.24bit.net',desc:'专注 Hi-Res/24bit 无损音乐分享与下载。',badge:'free'},
  {id:'dtwav-com',name:'杜威音乐',url:'https://dtwav.com',desc:'Hi-Res 无损音乐下载，音质出众。',badge:'free'},
  {id:'1music-cc-zh-cn',name:'1Music',url:'https://1music.cc/zh-CN',desc:'在线免费听歌，聚合多平台曲库。',badge:'free'},
  {id:'musopen-org',name:'Musopen',url:'https://musopen.org',desc:'免费古典音乐下载，版权解放的古典乐宝库。',badge:'free'},
  {id:'radio-garden',name:'Radio Garden',url:'https://radio.garden',desc:'全球电台地图可视化浏览，旋转地球收听世界电台。',badge:'free'},
  {id:'radio5-cn',name:'Radio5',url:'https://radio5.cn',desc:'国内在线电台聚合，各大广播收听一站搞定。',badge:'free'},
  {id:'tunein-com',name:'TuneIn Radio',url:'https://tunein.com',desc:'网络电台聚合平台，体育/新闻/音乐电台全覆盖。'},
  {id:'last-fm',name:'Last.fm',url:'https://www.last.fm',desc:'音乐社交平台，追踪收听历史，发现相似音乐。'},
  {id:'discogs-com',name:'Discogs',url:'https://www.discogs.com',desc:'全球最大唱片数据库与二手黑胶交易市场。'},
  {id:'open-spotify-com-browse-podcasts',name:'Spotify Podcast',url:'https://open.spotify.com/browse/podcasts',desc:'Spotify 播客平台，海量节目覆盖各类主题。'},
  {id:'anchor-fm',name:'Anchor',url:'https://anchor.fm',desc:'播客创作与发布平台，零成本开始你的播客。',badge:'free'},
  {id:'ttsmaker-cn',name:'TTS Maker',url:'https://ttsmaker.cn',desc:'AI 文字转语音工具，多种语言与音色可选。',badge:'free'},
  {id:'tongchuan-iflyrec-com',name:'讯飞通传',url:'https://tongchuan.iflyrec.com/',desc:'科大讯飞出品的实时语音转录工具，精准率高。',badge:'cn'},
  {id:'store-steampowered-com',name:'Steam',url:'https://store.steampowered.com',desc:'全球最大 PC 游戏平台，拥有海量游戏与社区功能。'},
  {id:'epicgames-com',name:'Epic Games',url:'https://www.epicgames.com',desc:'Epic 游戏商店，每周免费赠送 AAA 游戏。'},
  {id:'gog-com',name:'GOG',url:'https://www.gog.com',desc:'无 DRM 游戏商店，游戏购买永久拥有无限制。'},
  {id:'itch-io',name:'Itch.io',url:'https://itch.io',desc:'独立游戏发布与发现平台，创意小游戏聚集地。'},
  {id:'humblebundle-com',name:'Humble Bundle',url:'https://www.humblebundle.com',desc:'游戏捆绑销售平台，买游戏同时支持慈善事业。'},
  {id:'jidi520-com',name:'机地游戏',url:'https://jidi520.com',desc:'免费游戏单机资源下载，含本体/Mod/修改器，每日更新。',badge:'free'},
  {id:'steamzg-com',name:'SteamZG',url:'https://steamzg.com',desc:'Steam 游戏资源与攻略分享社区。',badge:'cn'},
  {id:'byrutgame-org',name:'ByRutGame',url:'https://byrutgame.org',desc:'PC 游戏资源下载站，更新及时。',badge:'free'},
  {id:'retroarch-com',name:'RetroArch',url:'https://retroarch.com',desc:'多合一游戏模拟器前端，支持数十种复古游戏平台。',badge:'free'},
  {id:'pcsx2-net',name:'PCSX2',url:'https://pcsx2.net',desc:'PlayStation 2 模拟器，效果出色兼容性好。',badge:'free'},
  {id:'ryujinx-org',name:'Ryujinx',url:'https://ryujinx.org',desc:'Nintendo Switch 模拟器，支持大量游戏。',badge:'free'},
  {id:'fcpic-nesbbs-com-game-html',name:'NES/FC 游戏',url:'https://fcpic.nesbbs.com/game.html',desc:'FC/NES 经典红白机游戏在线玩与 ROM 下载。',badge:'free'},
  {id:'poki-com-zh',name:'Poki',url:'https://poki.com/zh',desc:'免费在线小游戏平台，无需下载即玩。',badge:'free'},
  {id:'crazygames-com',name:'CrazyGames',url:'https://www.crazygames.com',desc:'免费浏览器游戏集合，品质游戏精选。',badge:'free'},
  {id:'classicjoy-games-zh',name:'ClassicJoy',url:'https://classicjoy.games/zh',desc:'经典老游戏在线体验，无需安装直接浏览器玩。',badge:'free'},
  {id:'oldswf-com',name:'OldSWF',url:'https://oldswf.com',desc:'Flash 小游戏怀旧合集，重温童年经典。',badge:'free'},
  {id:'ign-com',name:'IGN',url:'https://www.ign.com',desc:'全球顶级游戏媒体，评测/攻略/新闻全覆盖。'},
  {id:'gamefaqs-gamespot-com',name:'GameFAQs',url:'https://gamefaqs.gamespot.com',desc:'游戏攻略数据库，覆盖数十年经典游戏攻略。'},
  {id:'unity-com',name:'Unity',url:'https://unity.com',desc:'全球最流行的游戏引擎，移动游戏首选。'},
  {id:'godotengine-org',name:'Godot',url:'https://godotengine.org',desc:'完全开源免费的游戏引擎，正在快速崛起。',badge:'free'},
  {id:'ninite-com',name:'Ninite',url:'https://ninite.com',desc:'Windows 软件批量安装工具，一键安装常用软件。',badge:'free'},
  {id:'portableapps-com',name:'PortableApps',url:'https://portableapps.com',desc:'便携软件平台，U 盘随身携带，无需安装。',badge:'free'},
  {id:'softpedia-com',name:'Softpedia',url:'https://www.softpedia.com',desc:'全平台软件下载站，收录海量正版共享软件。'},
  {id:'majorgeeks-com',name:'MajorGeeks',url:'https://majorgeeks.com',desc:'老牌 Windows 工具软件下载站，质量有保证。'},
  {id:'chocolatey-org',name:'Chocolatey',url:'https://chocolatey.org',desc:'Windows 命令行包管理器，批量自动化安装。',badge:'free'},
  {id:'oldversion-com',name:'OldVersion',url:'https://oldversion.com',desc:'下载各软件旧版本，解决兼容性问题必备。'},
  {id:'brew-sh',name:'Homebrew',url:'https://brew.sh',desc:'macOS/Linux 最流行包管理器，一条命令安装软件。',badge:'free'},
  {id:'snapcraft-io',name:'Snapcraft',url:'https://snapcraft.io',desc:'Linux Snap 应用商店，覆盖发行版广泛。',badge:'free'},
  {id:'github-com-yt-dlp-yt-dlp',name:'yt-dlp',url:'https://github.com/yt-dlp/yt-dlp',desc:'功能最强的视频下载命令行工具，支持上千个网站。',badge:'free'},
  {id:'4kdownload-com',name:'4K Video Downloader',url:'https://4kdownload.com',desc:'桌面端视频下载工具，支持 YouTube 等主流平台。'},
  {id:'jdownloader-org',name:'JDownloader',url:'https://jdownloader.org',desc:'开源多线程下载管理器，支持大量网盘与视频源。',badge:'free'},
  {id:'internetdownloadmanager-com',name:'IDM',url:'https://internetdownloadmanager.com',desc:'老牌多线程下载加速工具，支持浏览器集成。'},
  {id:'1337x-to',name:'1337x',url:'https://1337x.to',desc:'界面整洁的种子搜索站，电影/剧集/游戏资源丰富。'},
  {id:'yts-mx',name:'YTS',url:'https://yts.mx',desc:'高质量电影种子，体积小画质优，热门影片必备。'},
  {id:'eztv-ag',name:'EZTV',url:'https://eztv.ag',desc:'专注剧集资源的种子站点，更新及时。'},
  {id:'btdb-to',name:'BTDB',url:'https://btdb.to',desc:'BT 种子数据库搜索，资源量庞大。'},
  {id:'demonoid-se',name:'Demonoid',url:'https://demonoid.se',desc:'老牌半私人种子社区，资源质量较高。'},
  {id:'bt-mojiez-net',name:'摩羯座BT',url:'https://bt.mojiez.net',desc:'专注电影、电视剧资源的 BT 磁力站。',badge:'free'},
  {id:'sidhub-cc',name:'SeedHub',url:'https://sidhub.cc',desc:'专注分享优质影视资源的磁力/BT 网站。',badge:'free'},
  {id:'pomo-mom',name:'POMO 4K',url:'https://pomo.mom',desc:'以 4K 资源为主的磁力资源站，画质极高。',badge:'free'},
  {id:'cilixiong-org',name:'磁力熊',url:'https://www.cilixiong.org',desc:'界面清爽的高分影视资源下载站。',badge:'free'},
  {id:'qbittorrent-org',name:'qBittorrent',url:'https://qbittorrent.org',desc:'开源免费 BT 下载客户端，无广告轻量好用。',badge:'free'},
  {id:'transmissionbt-com',name:'Transmission',url:'https://transmissionbt.com',desc:'极简 BT 客户端，Mac/Linux 用户首选。',badge:'free'},
  {id:'aria2-github-io',name:'aria2',url:'https://aria2.github.io',desc:'超轻量命令行下载工具，支持 HTTP/FTP/BT/磁力。',badge:'free'},
  {id:'play-google-com',name:'Google Play',url:'https://play.google.com',desc:'Android 官方应用商店，全球最大应用生态。'},
  {id:'f-droid-org',name:'F-Droid',url:'https://f-droid.org',desc:'Android 开源应用商店，完全免费无追踪。',badge:'free'},
  {id:'apkmirror-com',name:'APKMirror',url:'https://www.apkmirror.com',desc:'APK 安装包下载，版本全面，安全可信。',badge:'free'},
  {id:'apps-apple-com',name:'App Store',url:'https://apps.apple.com',desc:'苹果官方应用商店，iOS/iPadOS/macOS 应用中心。'},
  {id:'appgallery-huawei-com',name:'Huawei AppGallery',url:'https://appgallery.huawei.com',desc:'华为应用商店，支持鸿蒙与 Android 应用分发。',badge:'cn'},
  {id:'altstore-io',name:'AltStore',url:'https://altstore.io',desc:'iOS 侧载工具，无需越狱安装第三方应用。'},
  {id:'sideloadly-io',name:'Sideloadly',url:'https://sideloadly.io',desc:'iOS/iPadOS 侧载工具，操作简单支持多种签名。'},
  {id:'topjohnwu-github-io-magisk',name:'Magisk',url:'https://topjohnwu.github.io/Magisk/',desc:'Android 系统级 ROOT 工具，无痕模式过银行检测。',badge:'open'},
  {id:'xda-developers-com',name:'XDA Developers',url:'https://xda-developers.com',desc:'全球最大 Android 开发者社区，刷机/ROOT 论坛。'},
  {id:'lineageos-org',name:'LineageOS',url:'https://lineageos.org',desc:'最流行的第三方 Android 系统，隐私友好开源。',badge:'free'},
  {id:'twrp-me',name:'TWRP',url:'https://twrp.me',desc:'第三方 Android Recovery，刷机备份必备工具。',badge:'free'},
  {id:'ubuntu-com',name:'Ubuntu',url:'https://ubuntu.com',desc:'全球最流行 Linux 发行版，新手友好，生态完善。',badge:'free'},
  {id:'archlinux-org',name:'Arch Linux',url:'https://archlinux.org',desc:'滚动发行版，极简设计，由用户自主掌控一切。',badge:'free'},
  {id:'deepin-org',name:'深度系统',url:'https://deepin.org',desc:'国产 Linux 桌面系统，UI 优美，中文支持最佳。',badge:'cn'},
  {id:'system76-com-pop-os',name:'Pop!_OS',url:'https://system76.com/pop-os',desc:'面向开发者和创作者的 Linux，NVIDIA 驱动开箱即用。',badge:'free'},
  {id:'uniontech-com',name:'统信 UOS',url:'https://www.uniontech.com',desc:'国产商用 Linux 系统，政企场景广泛适配。',badge:'cn'},
  {id:'brew-sh-1',name:'Homebrew',url:'https://brew.sh',desc:'macOS/Linux 最流行包管理器，一条命令安装软件。',badge:'free'},
  {id:'iterm2-com',name:'iTerm2',url:'https://iterm2.com',desc:'macOS 最佳终端替代品，功能强大高度可定制。',badge:'free'},
  {id:'ohmyz-sh',name:'Oh My Zsh',url:'https://ohmyz.sh',desc:'Zsh 配置管理框架，数百个插件与主题。',badge:'free'},
  {id:'cockpit-project-org',name:'Cockpit',url:'https://cockpit-project.org',desc:'Web 图形化 Linux 服务器管理界面，运维利器。',badge:'free'},
  {id:'explainshell-com',name:'Explainshell',url:'https://explainshell.com',desc:'粘贴 Shell 命令即可拆解每个参数含义。',badge:'free'},
  {id:'shellcheck-net',name:'ShellCheck',url:'https://shellcheck.net',desc:'Shell 脚本静态分析工具，发现潜在 Bug。',badge:'free'},
  {id:'gnome-org',name:'GNOME',url:'https://gnome.org',desc:'最流行 Linux 桌面环境，现代简洁设计风格。',badge:'free'},
  {id:'kde-org',name:'KDE Plasma',url:'https://kde.org',desc:'功能最丰富的 Linux 桌面，高度可定制化。',badge:'free'},
  {id:'reddit-com',name:'Reddit',url:'https://reddit.com',desc:'全球最大链接分享社区，几乎涵盖所有话题圈子。'},
  {id:'quora-com',name:'Quora',url:'https://quora.com',desc:'英文高质量问答平台，专业人士聚集。'},
  {id:'medium-com',name:'Medium',url:'https://medium.com',desc:'英文文章写作与阅读平台，深度内容聚集地。'},
  {id:'news-ycombinator-com',name:'Hacker News',url:'https://news.ycombinator.com',desc:'YC 旗下科技资讯社区，技术圈最重要讨论广场。'},
  {id:'en-wikipedia-org',name:'Wikipedia EN',url:'https://en.wikipedia.org',desc:'英文维基百科，全球最大知识数据库。',badge:'free'},
  {id:'bbc-com',name:'BBC',url:'https://bbc.com',desc:'英国广播公司，国际新闻权威媒体。'},
  {id:'theverge-com',name:'The Verge',url:'https://www.theverge.com',desc:'科技媒体标杆，覆盖科技、文化、科学，报道质量高。'},
  {id:'chiebukuro-yahoo-co-jp',name:'知恵袋',url:'https://chiebukuro.yahoo.co.jp',desc:'日本最大知识问答社区，解决日语疑问必备。'},
  {id:'hatena-ne-jp',name:'はてな',url:'https://hatena.ne.jp',desc:'日本博客与问答平台，技术与文化内容丰富。'},
  {id:'naver-com',name:'Naver',url:'https://naver.com',desc:'韩国最大搜索引擎与门户网站。'},
  {id:'lemonde-fr',name:'Le Monde',url:'https://lemonde.fr',desc:'法国最具影响力日报，世界新闻高质量报道。'},
  {id:'spiegel-de',name:'Der Spiegel',url:'https://spiegel.de',desc:'德国权威新闻周刊，欧洲政治经济深度报道。'},
  {id:'789bh-com',name:'https://789bh.com/',url:'https://789bh.com/',desc:'https://789bh.com/ - 从导�航站提取的资源'},
  {id:'xn--kbtq9uklxgkj-top',name:'http://xn--kbtq9uklxgkj.top/',url:'http://xn--kbtq9uklxgkj.top/',desc:'http://xn--kbtq9uklxgkj.top/ - 从导�航站提取的资源'},
  {id:'znys-top',name:'https://znys.top/',url:'https://znys.top/',desc:'https://znys.top/ - 从导�航站提取的资源'},
  {id:'yun2s2lxsduo22-top',name:'https://yun2s2lxsduo22.top/',url:'https://yun2s2lxsduo22.top/',desc:'https://yun2s2lxsduo22.top/ - 从导�航站提取的资源'},
  {id:'jianyunys-com',name:'https://jianyunys.com/',url:'https://jianyunys.com/',desc:'https://jianyunys.com/ - 从导�航站提取的资源'},
  {id:'xx01-xiguatv-xyz',name:'https://xx01.xiguatv.xyz/',url:'https://xx01.xiguatv.xyz/',desc:'https://xx01.xiguatv.xyz/ - 从导�航站提取的资源'},
  {id:'cilixiong-xyz',name:'https://www.cilixiong.xyz/',url:'https://www.cilixiong.xyz/',desc:'https://www.cilixiong.xyz/ - 从导�航站提取的资源'},
  {id:'dmhyy-com',name:'https://dmhyy.com/',url:'https://dmhyy.com/',desc:'https://dmhyy.com/ - 从导�航站提取的资源'},
  {id:'libvio-link',name:'https://www.libvio.link/',url:'https://www.libvio.link/',desc:'https://www.libvio.link/ - 从导�航站提取的资源'},
  {id:'bttwo-me',name:'https://www.bttwo.me/',url:'https://www.bttwo.me/',desc:'https://www.bttwo.me/ - 从导�航站提取的资源'},
  {id:'duse1-com',name:'https://www.duse1.com/',url:'https://www.duse1.com/',desc:'https://www.duse1.com/ - 从导�航站提取的资源'},
  {id:'jciyuan-com',name:'https://jciyuan.com/',url:'https://jciyuan.com/',desc:'https://jciyuan.com/ - 从导�航站提取的资源'},
  {id:'ezdmw-site',name:'https://www.ezdmw.site/',url:'https://www.ezdmw.site/',desc:'https://www.ezdmw.site/ - 从导�航站提取的资源'},
  {id:'fanchawu-cc',name:'https://www.fanchawu.cc/',url:'https://www.fanchawu.cc/',desc:'https://www.fanchawu.cc/ - 从导�航站提取的资源'},
  {id:'laohuabao-com',name:'http://www.laohuabao.com/',url:'http://www.laohuabao.com/',desc:'http://www.laohuabao.com/ - 从导�航站提取的资源'},
  {id:'creative-comic-tw-zh',name:'https://www.creative-comic.tw/zh/',url:'https://www.creative-comic.tw/zh/',desc:'https://www.creative-comic.tw/zh/ - 从导�航站提取的资源'},
  {id:'manhuagou-net',name:'https://www.manhuagou.net/',url:'https://www.manhuagou.net/',desc:'https://www.manhuagou.net/ - 从导�航站提取的资源'},
  {id:'mfgalleria-com',name:'https://www.mfgalleria.com/',url:'https://www.mfgalleria.com/',desc:'https://www.mfgalleria.com/ - 从导�航站提取的资源'},
  {id:'kanman-com',name:'https://www.kanman.com/',url:'https://www.kanman.com/',desc:'https://www.kanman.com/ - 从导�航站提取的资源'},
  {id:'manwawang-com',name:'https://manwawang.com/',url:'https://manwawang.com/',desc:'https://manwawang.com/ - 从导�航站提取的资源'},
  {id:'yymanhua-com',name:'https://www.yymanhua.com/',url:'https://www.yymanhua.com/',desc:'https://www.yymanhua.com/ - 从导�航站提取的资源'},
  {id:'mhx12-com',name:'https://mhx12.com/',url:'https://mhx12.com/',desc:'https://mhx12.com/ - 从导�航站提取的资源'},
  {id:'manben-com',name:'https://www.manben.com/',url:'https://www.manben.com/',desc:'https://www.manben.com/ - 从导�航站提取的资源'},
  {id:'gufengmh-com',name:'https://www.gufengmh.com/',url:'https://www.gufengmh.com/',desc:'https://www.gufengmh.com/ - 从导�航站提取的资源'},
  {id:'komiic-com',name:'https://komiic.com/',url:'https://komiic.com/',desc:'https://komiic.com/ - 从导�航站提取的资源'},
  {id:'mangacopy-com',name:'https://www.mangacopy.com/',url:'https://www.mangacopy.com/',desc:'https://www.mangacopy.com/ - 从导�航站提取的资源'},
  {id:'cn-baozimhcn-com',name:'https://cn.baozimhcn.com/',url:'https://cn.baozimhcn.com/',desc:'https://cn.baozimhcn.com/ - 从导�航站提取的资源'},
  {id:'hisoman-com',name:'https://www.hisoman.com/',url:'https://www.hisoman.com/',desc:'https://www.hisoman.com/ - 从导�航站提取的资源'},
  {id:'dashumanhua-com',name:'https://www.dashumanhua.com/',url:'https://www.dashumanhua.com/',desc:'https://www.dashumanhua.com/ - 从导�航站提取的资源'},
  {id:'dm5-com',name:'https://www.dm5.com/',url:'https://www.dm5.com/',desc:'https://www.dm5.com/ - 从导�航站提取的资源'},
  {id:'manhua-idmzj-com',name:'https://manhua.idmzj.com/',url:'https://manhua.idmzj.com/',desc:'https://manhua.idmzj.com/ - 从导�航站提取的资源'},
  {id:'manhua-sfacg-com',name:'https://manhua.sfacg.com/',url:'https://manhua.sfacg.com/',desc:'https://manhua.sfacg.com/ - 从导�航站提取的资源'},
];
